{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Mask R-CNN - Train on Shapes Dataset\n",
    "\n",
    "\n",
    "This notebook shows how to train Mask R-CNN on your own dataset. To keep things simple we use a synthetic dataset of shapes (squares, triangles, and circles) which enables fast training. You'd still need a GPU, though, because the network backbone is a Resnet101, which would be too slow to train on a CPU. On a GPU, you can start to get okay-ish results in a few minutes, and good results in less than an hour.\n",
    "\n",
    "The code of the *Shapes* dataset is included below. It generates images on the fly, so it doesn't require downloading any data. And it can generate images of any size, so we pick a small image size to train faster. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import sys\n",
    "import random\n",
    "import math\n",
    "import re\n",
    "import time\n",
    "import numpy as np\n",
    "import cv2\n",
    "import matplotlib\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Root directory of the project\n",
    "ROOT_DIR = os.path.abspath(\"./\")\n",
    "\n",
    "# Import Mask RCNN\n",
    "sys.path.append(ROOT_DIR)  # To find local version of the library\n",
    "from mrcnn import utils\n",
    "import mrcnn.model as modellib\n",
    "from mrcnn import visualize\n",
    "from mrcnn.model import log\n",
    "\n",
    "%matplotlib inline \n",
    "\n",
    "# Directory to save logs and trained model\n",
    "MODEL_DIR = os.path.join(ROOT_DIR, \"logs\")\n",
    "\n",
    "# Local path to trained weights file\n",
    "COCO_MODEL_PATH = os.path.join(ROOT_DIR, \"mask_rcnn_coco.h5\")\n",
    "# Download COCO trained weights from Releases if needed\n",
    "if not os.path.exists(COCO_MODEL_PATH):\n",
    "    utils.download_trained_weights(COCO_MODEL_PATH)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Configurations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Configurations:\n",
      "BACKBONE                       resnet101\n",
      "BACKBONE_STRIDES               [4, 8, 16, 32, 64]\n",
      "BATCH_SIZE                     8\n",
      "BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]\n",
      "COMPUTE_BACKBONE_SHAPE         None\n",
      "DETECTION_MAX_INSTANCES        100\n",
      "DETECTION_MIN_CONFIDENCE       0.7\n",
      "DETECTION_NMS_THRESHOLD        0.3\n",
      "FPN_CLASSIF_FC_LAYERS_SIZE     1024\n",
      "GPU_COUNT                      1\n",
      "GRADIENT_CLIP_NORM             5.0\n",
      "IMAGES_PER_GPU                 8\n",
      "IMAGE_CHANNEL_COUNT            3\n",
      "IMAGE_MAX_DIM                  256\n",
      "IMAGE_META_SIZE                24\n",
      "IMAGE_MIN_DIM                  256\n",
      "IMAGE_MIN_SCALE                0\n",
      "IMAGE_RESIZE_MODE              square\n",
      "IMAGE_SHAPE                    [256 256   3]\n",
      "LEARNING_MOMENTUM              0.9\n",
      "LEARNING_RATE                  0.001\n",
      "LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}\n",
      "MASK_POOL_SIZE                 14\n",
      "MASK_SHAPE                     [28, 28]\n",
      "MAX_GT_INSTANCES               100\n",
      "MEAN_PIXEL                     [123.7 116.8 103.9]\n",
      "MINI_MASK_SHAPE                (56, 56)\n",
      "NAME                           Brain\n",
      "NUM_CLASSES                    12\n",
      "POOL_SIZE                      7\n",
      "POST_NMS_ROIS_INFERENCE        1000\n",
      "POST_NMS_ROIS_TRAINING         2000\n",
      "PRE_NMS_LIMIT                  6000\n",
      "ROI_POSITIVE_RATIO             0.33\n",
      "RPN_ANCHOR_RATIOS              [0.5, 1, 2]\n",
      "RPN_ANCHOR_SCALES              (8, 16, 32, 64, 128)\n",
      "RPN_ANCHOR_STRIDE              1\n",
      "RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]\n",
      "RPN_NMS_THRESHOLD              0.7\n",
      "RPN_TRAIN_ANCHORS_PER_IMAGE    256\n",
      "STEPS_PER_EPOCH                100\n",
      "TOP_DOWN_PYRAMID_SIZE          256\n",
      "TRAIN_BN                       False\n",
      "TRAIN_ROIS_PER_IMAGE           32\n",
      "USE_MINI_MASK                  True\n",
      "USE_RPN_ROIS                   True\n",
      "VALIDATION_STEPS               5\n",
      "WEIGHT_DECAY                   0.0001\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from brain import BrainsConfig\n",
    "config = BrainsConfig()\n",
    "config.display()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Notebook Preferences"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_ax(rows=1, cols=1, size=8):\n",
    "    \"\"\"Return a Matplotlib Axes array to be used in\n",
    "    all visualizations in the notebook. Provide a\n",
    "    central point to control graph sizes.\n",
    "    \n",
    "    Change the default size attribute to control the size\n",
    "    of rendered images\n",
    "    \"\"\"\n",
    "    _, ax = plt.subplots(rows, cols, figsize=(size*cols, size*rows))\n",
    "    return ax"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Dataset\n",
    "\n",
    "Create a synthetic dataset\n",
    "\n",
    "Extend the Dataset class and add a method to load the shapes dataset, `load_shapes()`, and override the following methods:\n",
    "\n",
    "* load_image()\n",
    "* load_mask()\n",
    "* image_reference()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total data number is 6727\n",
      "Training data number is 5381\n",
      "Val data number is 1346\n"
     ]
    }
   ],
   "source": [
    "from preprocess import dataset_preprocess\n",
    "dataset_preprocess()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "from brain import BrainsDataset\n",
    "\n",
    "# Dataset path\n",
    "train_data_path = './../dataset/Processed/train'\n",
    "val_data_path = './../dataset/Processed/val'\n",
    "\n",
    "# Training dataset\n",
    "dataset_train = BrainsDataset()\n",
    "dataset_train.load_brains(train_data_path)\n",
    "dataset_train.prepare()\n",
    "\n",
    "\n",
    "# Validation dataset\n",
    "dataset_val = BrainsDataset()\n",
    "dataset_val.load_brains(val_data_path)\n",
    "dataset_val.prepare()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Create Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create model in training mode\n",
    "model = modellib.MaskRCNN(mode=\"training\", config=config, model_dir=MODEL_DIR)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "# Which weights to start with?\n",
    "init_with = \"coco\"  # imagenet, coco, or last\n",
    "\n",
    "if init_with == \"imagenet\":\n",
    "    model.load_weights(model.get_imagenet_weights(), by_name=True)\n",
    "elif init_with == \"coco\":\n",
    "    # Load weights trained on MS COCO, but skip layers that\n",
    "    # are different due to the different number of classes\n",
    "    # See README for instructions to download the COCO weights\n",
    "    model.load_weights(COCO_MODEL_PATH, by_name=True,\n",
    "                       exclude=[\"mrcnn_class_logits\", \"mrcnn_bbox_fc\", \n",
    "                                \"mrcnn_bbox\", \"mrcnn_mask\"])\n",
    "elif init_with == \"last\":\n",
    "    # Load the last model you trained and continue training\n",
    "    model.load_weights(model.find_last(), by_name=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Training\n",
    "\n",
    "Train in two stages:\n",
    "1. Only the heads. Here we're freezing all the backbone layers and training only the randomly initialized layers (i.e. the ones that we didn't use pre-trained weights from MS COCO). To train only the head layers, pass `layers='heads'` to the `train()` function.\n",
    "\n",
    "2. Fine-tune all layers. For this simple example it's not necessary, but we're including it to show the process. Simply pass `layers=\"all` to train all layers."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use the retry module or similar alternatives.\n",
      "\n",
      "Starting at epoch 0. LR=0.001\n",
      "\n",
      "Checkpoint Path: /Users/dodo/Documents/projects/maskrcnn/train/logs/brain20181204T0108/mask_rcnn_brain_{epoch:04d}.h5\n",
      "Selecting layers to train\n",
      "fpn_c5p5               (Conv2D)\n",
      "fpn_c4p4               (Conv2D)\n",
      "fpn_c3p3               (Conv2D)\n",
      "fpn_c2p2               (Conv2D)\n",
      "fpn_p5                 (Conv2D)\n",
      "fpn_p2                 (Conv2D)\n",
      "fpn_p3                 (Conv2D)\n",
      "fpn_p4                 (Conv2D)\n",
      "In model:  rpn_model\n",
      "    rpn_conv_shared        (Conv2D)\n",
      "    rpn_class_raw          (Conv2D)\n",
      "    rpn_bbox_pred          (Conv2D)\n",
      "mrcnn_mask_conv1       (TimeDistributed)\n",
      "mrcnn_mask_bn1         (TimeDistributed)\n",
      "mrcnn_mask_conv2       (TimeDistributed)\n",
      "mrcnn_mask_bn2         (TimeDistributed)\n",
      "mrcnn_class_conv1      (TimeDistributed)\n",
      "mrcnn_class_bn1        (TimeDistributed)\n",
      "mrcnn_mask_conv3       (TimeDistributed)\n",
      "mrcnn_mask_bn3         (TimeDistributed)\n",
      "mrcnn_class_conv2      (TimeDistributed)\n",
      "mrcnn_class_bn2        (TimeDistributed)\n",
      "mrcnn_mask_conv4       (TimeDistributed)\n",
      "mrcnn_mask_bn4         (TimeDistributed)\n",
      "mrcnn_bbox_fc          (TimeDistributed)\n",
      "mrcnn_mask_deconv      (TimeDistributed)\n",
      "mrcnn_class_logits     (TimeDistributed)\n",
      "mrcnn_mask             (TimeDistributed)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.\n",
      "  \"Converting sparse IndexedSlices to a dense Tensor of unknown shape. \"\n",
      "/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/keras/engine/training_generator.py:47: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the`keras.utils.Sequence class.\n",
      "  UserWarning('Using a generator with `use_multiprocessing=True`'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Error processing image {'id': 5177, 'source': 'brains', 'path': './../dataset/Processed/train/5_t1_w2r_40.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 1797, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w1r_26.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 5177, 'source': 'brains', 'path': './../dataset/Processed/train/5_t1_w2r_40.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 5177, 'source': 'brains', 'path': './../dataset/Processed/train/5_t1_w2r_40.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 5177, 'source': 'brains', 'path': './../dataset/Processed/train/5_t1_w2r_40.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 5177, 'source': 'brains', 'path': './../dataset/Processed/train/5_t1_w2r_40.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 5177, 'source': 'brains', 'path': './../dataset/Processed/train/5_t1_w2r_40.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 5177, 'source': 'brains', 'path': './../dataset/Processed/train/5_t1_w2r_40.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 780, 'source': 'brains', 'path': './../dataset/Processed/val/7_t2_w1_18.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 5177, 'source': 'brains', 'path': './../dataset/Processed/train/5_t1_w2r_40.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 780, 'source': 'brains', 'path': './../dataset/Processed/val/7_t2_w1_18.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 780, 'source': 'brains', 'path': './../dataset/Processed/val/7_t2_w1_18.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1797, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w1r_26.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 780, 'source': 'brains', 'path': './../dataset/Processed/val/7_t2_w1_18.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 780, 'source': 'brains', 'path': './../dataset/Processed/val/7_t2_w1_18.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 780, 'source': 'brains', 'path': './../dataset/Processed/val/7_t2_w1_18.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 780, 'source': 'brains', 'path': './../dataset/Processed/val/7_t2_w1_18.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 1797, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w1r_26.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 780, 'source': 'brains', 'path': './../dataset/Processed/val/7_t2_w1_18.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 1797, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w1r_26.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 490, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2_16.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1797, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w1r_26.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1897, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w2r_3.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1797, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w1r_26.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 1897, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w2r_3.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "ERROR:root:Error processing image {'id': 1797, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w1r_26.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 490, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2_16.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 490, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2_16.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1797, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w1r_26.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 1897, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w2r_3.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 490, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2_16.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 490, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2_16.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 490, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2_16.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1897, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w2r_3.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 490, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2_16.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 5362, 'source': 'brains', 'path': './../dataset/Processed/train/5_t2_w2r_34.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 490, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2_16.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1897, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w2r_3.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 5362, 'source': 'brains', 'path': './../dataset/Processed/train/5_t2_w2r_34.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "ERROR:root:Error processing image {'id': 728, 'source': 'brains', 'path': './../dataset/Processed/val/7_t1_w2r_14.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 5362, 'source': 'brains', 'path': './../dataset/Processed/train/5_t2_w2r_34.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "ERROR:root:Error processing image {'id': 1897, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w2r_3.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1897, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w2r_3.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "ERROR:root:Error processing image {'id': 728, 'source': 'brains', 'path': './../dataset/Processed/val/7_t1_w2r_14.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1414, 'source': 'brains', 'path': './../dataset/Processed/train/148_t2_w1r_27.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 728, 'source': 'brains', 'path': './../dataset/Processed/val/7_t1_w2r_14.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 1414, 'source': 'brains', 'path': './../dataset/Processed/train/148_t2_w1r_27.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1897, 'source': 'brains', 'path': './../dataset/Processed/train/148_t4_w2r_3.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 728, 'source': 'brains', 'path': './../dataset/Processed/val/7_t1_w2r_14.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 728, 'source': 'brains', 'path': './../dataset/Processed/val/7_t1_w2r_14.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "ERROR:root:Error processing image {'id': 728, 'source': 'brains', 'path': './../dataset/Processed/val/7_t1_w2r_14.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 728, 'source': 'brains', 'path': './../dataset/Processed/val/7_t1_w2r_14.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 728, 'source': 'brains', 'path': './../dataset/Processed/val/7_t1_w2r_14.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 5362, 'source': 'brains', 'path': './../dataset/Processed/train/5_t2_w2r_34.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 1197, 'source': 'brains', 'path': './../dataset/Processed/val/7_t4_w1_5.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1414, 'source': 'brains', 'path': './../dataset/Processed/train/148_t2_w1r_27.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 5362, 'source': 'brains', 'path': './../dataset/Processed/train/5_t2_w2r_34.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 4288, 'source': 'brains', 'path': './../dataset/Processed/train/4_t2_w1r_19.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 5362, 'source': 'brains', 'path': './../dataset/Processed/train/5_t2_w2r_34.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "ERROR:root:Error processing image {'id': 5362, 'source': 'brains', 'path': './../dataset/Processed/train/5_t2_w2r_34.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 1197, 'source': 'brains', 'path': './../dataset/Processed/val/7_t4_w1_5.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1197, 'source': 'brains', 'path': './../dataset/Processed/val/7_t4_w1_5.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 5362, 'source': 'brains', 'path': './../dataset/Processed/train/5_t2_w2r_34.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1197, 'source': 'brains', 'path': './../dataset/Processed/val/7_t4_w1_5.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 4288, 'source': 'brains', 'path': './../dataset/Processed/train/4_t2_w1r_19.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 1197, 'source': 'brains', 'path': './../dataset/Processed/val/7_t4_w1_5.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 4288, 'source': 'brains', 'path': './../dataset/Processed/train/4_t2_w1r_19.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 1197, 'source': 'brains', 'path': './../dataset/Processed/val/7_t4_w1_5.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "ERROR:root:Error processing image {'id': 1197, 'source': 'brains', 'path': './../dataset/Processed/val/7_t4_w1_5.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 1414, 'source': 'brains', 'path': './../dataset/Processed/train/148_t2_w1r_27.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1197, 'source': 'brains', 'path': './../dataset/Processed/val/7_t4_w1_5.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1414, 'source': 'brains', 'path': './../dataset/Processed/train/148_t2_w1r_27.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1414, 'source': 'brains', 'path': './../dataset/Processed/train/148_t2_w1r_27.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "ERROR:root:Error processing image {'id': 570, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2r_45.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "ERROR:root:Error processing image {'id': 570, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2r_45.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 570, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2r_45.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 1414, 'source': 'brains', 'path': './../dataset/Processed/train/148_t2_w1r_27.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 4288, 'source': 'brains', 'path': './../dataset/Processed/train/4_t2_w1r_19.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 570, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2r_45.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 1414, 'source': 'brains', 'path': './../dataset/Processed/train/148_t2_w1r_27.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 4288, 'source': 'brains', 'path': './../dataset/Processed/train/4_t2_w1r_19.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 570, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2r_45.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "ERROR:root:Error processing image {'id': 570, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2r_45.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 570, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2r_45.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 570, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w2r_45.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 470, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w1r_41.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "ERROR:root:Error processing image {'id': 4288, 'source': 'brains', 'path': './../dataset/Processed/train/4_t2_w1r_19.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 4288, 'source': 'brains', 'path': './../dataset/Processed/train/4_t2_w1r_19.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 4288, 'source': 'brains', 'path': './../dataset/Processed/train/4_t2_w1r_19.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 470, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w1r_41.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 470, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w1r_41.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 470, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w1r_41.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 470, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w1r_41.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understoodERROR:root:Error processing image {'id': 470, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w1r_41.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n",
      "ERROR:root:Error processing image {'id': 470, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w1r_41.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "ERROR:root:Error processing image {'id': 470, 'source': 'brains', 'path': './../dataset/Processed/val/7_orig_w1r_41.npy'}\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n",
      "    use_mini_mask=config.USE_MINI_MASK)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n",
      "    mask, class_ids = dataset.load_mask(image_id)\n",
      "  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n",
      "    each_class = np.ones(seg.shape[0], seg.shape[1])\n",
      "  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n",
      "    a = empty(shape, dtype, order)\n",
      "TypeError: data type not understood\n",
      "\n",
      "\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "data type not understood",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRemoteTraceback\u001b[0m                           Traceback (most recent call last)",
      "\u001b[0;31mRemoteTraceback\u001b[0m: \n\"\"\"\nTraceback (most recent call last):\n  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/multiprocessing/pool.py\", line 119, in worker\n    result = (True, func(*args, **kwds))\n  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/keras/utils/data_utils.py\", line 626, in next_sample\n    return six.next(_SHARED_SEQUENCES[uid])\n  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1710, in data_generator\n    use_mini_mask=config.USE_MINI_MASK)\n  File \"/Users/dodo/Documents/projects/maskrcnn/train/mrcnn/model.py\", line 1213, in load_image_gt\n    mask, class_ids = dataset.load_mask(image_id)\n  File \"/Users/dodo/Documents/projects/maskrcnn/train/brain.py\", line 106, in load_mask\n    each_class = np.ones(seg.shape[0], seg.shape[1])\n  File \"/Users/dodo/.conda/envs/py3/lib/python3.6/site-packages/numpy/core/numeric.py\", line 188, in ones\n    a = empty(shape, dtype, order)\nTypeError: data type not understood\n\"\"\"",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-8-83fb3ae74319>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      6\u001b[0m             \u001b[0mlearning_rate\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mLEARNING_RATE\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m             \u001b[0mepochs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 8\u001b[0;31m             layers='heads')\n\u001b[0m",
      "\u001b[0;32m~/Documents/projects/maskrcnn/train/mrcnn/model.py\u001b[0m in \u001b[0;36mtrain\u001b[0;34m(self, train_dataset, val_dataset, learning_rate, epochs, layers, augmentation, custom_callbacks, no_augmentation_sources)\u001b[0m\n\u001b[1;32m   2373\u001b[0m             \u001b[0mmax_queue_size\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m100\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2374\u001b[0m             \u001b[0mworkers\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mworkers\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2375\u001b[0;31m             \u001b[0muse_multiprocessing\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2376\u001b[0m         )\n\u001b[1;32m   2377\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mepoch\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmax\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mepoch\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mepochs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/py3/lib/python3.6/site-packages/keras/legacy/interfaces.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     89\u001b[0m                 warnings.warn('Update your `' + object_name + '` call to the ' +\n\u001b[1;32m     90\u001b[0m                               'Keras 2 API: ' + signature, stacklevel=2)\n\u001b[0;32m---> 91\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     92\u001b[0m         \u001b[0mwrapper\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_original_function\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     93\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mwrapper\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/py3/lib/python3.6/site-packages/keras/engine/training.py\u001b[0m in \u001b[0;36mfit_generator\u001b[0;34m(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)\u001b[0m\n\u001b[1;32m   1416\u001b[0m             \u001b[0muse_multiprocessing\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0muse_multiprocessing\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1417\u001b[0m             \u001b[0mshuffle\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mshuffle\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1418\u001b[0;31m             initial_epoch=initial_epoch)\n\u001b[0m\u001b[1;32m   1419\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1420\u001b[0m     \u001b[0;34m@\u001b[0m\u001b[0minterfaces\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlegacy_generator_methods_support\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/py3/lib/python3.6/site-packages/keras/engine/training_generator.py\u001b[0m in \u001b[0;36mfit_generator\u001b[0;34m(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)\u001b[0m\n\u001b[1;32m    179\u001b[0m             \u001b[0mbatch_index\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    180\u001b[0m             \u001b[0;32mwhile\u001b[0m \u001b[0msteps_done\u001b[0m \u001b[0;34m<\u001b[0m \u001b[0msteps_per_epoch\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 181\u001b[0;31m                 \u001b[0mgenerator_output\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnext\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0moutput_generator\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    182\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    183\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mhasattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mgenerator_output\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'__len__'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/py3/lib/python3.6/site-packages/keras/utils/data_utils.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    707\u001b[0m                     \u001b[0;34m\"`use_multiprocessing=False, workers > 1`.\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    708\u001b[0m                     \"For more information see issue #1638.\")\n\u001b[0;32m--> 709\u001b[0;31m             \u001b[0msix\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreraise\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/.conda/envs/py3/lib/python3.6/site-packages/six.py\u001b[0m in \u001b[0;36mreraise\u001b[0;34m(tp, value, tb)\u001b[0m\n\u001b[1;32m    691\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    692\u001b[0m                 \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 693\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    694\u001b[0m         \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    695\u001b[0m             \u001b[0mvalue\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/py3/lib/python3.6/site-packages/keras/utils/data_utils.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    683\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    684\u001b[0m             \u001b[0;32mwhile\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_running\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 685\u001b[0;31m                 \u001b[0minputs\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mqueue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mblock\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    686\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mqueue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtask_done\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    687\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0minputs\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/py3/lib/python3.6/multiprocessing/pool.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    642\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_value\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    643\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 644\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_value\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    645\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    646\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_set\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mi\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mobj\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: data type not understood"
     ]
    }
   ],
   "source": [
    "# Train the head branches\n",
    "# Passing layers=\"heads\" freezes all layers except the head\n",
    "# layers. You can also pass a regular expression to select\n",
    "# which layers to train by name pattern.\n",
    "model.train(dataset_train, dataset_val, \n",
    "            learning_rate=config.LEARNING_RATE, \n",
    "            epochs=1, \n",
    "            layers='heads')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "# Fine tune all layers\n",
    "# Passing layers=\"all\" trains all layers. You can also \n",
    "# pass a regular expression to select which layers to\n",
    "# train by name pattern.\n",
    "model.train(dataset_train, dataset_val, \n",
    "            learning_rate=config.LEARNING_RATE / 10,\n",
    "            epochs=2, \n",
    "            layers=\"all\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# Save weights\n",
    "# Typically not needed because callbacks save after every epoch\n",
    "# Uncomment to save manually\n",
    "# model_path = os.path.join(MODEL_DIR, \"mask_rcnn_shapes.h5\")\n",
    "# model.keras_model.save_weights(model_path)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Detection"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "class InferenceConfig(ShapesConfig):\n",
    "    GPU_COUNT = 1\n",
    "    IMAGES_PER_GPU = 1\n",
    "\n",
    "inference_config = InferenceConfig()\n",
    "\n",
    "# Recreate the model in inference mode\n",
    "model = modellib.MaskRCNN(mode=\"inference\", \n",
    "                          config=inference_config,\n",
    "                          model_dir=MODEL_DIR)\n",
    "\n",
    "# Get path to saved weights\n",
    "# Either set a specific path or find last trained weights\n",
    "# model_path = os.path.join(ROOT_DIR, \".h5 file name here\")\n",
    "model_path = model.find_last()\n",
    "\n",
    "# Load trained weights\n",
    "print(\"Loading weights from \", model_path)\n",
    "model.load_weights(model_path, by_name=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# Test on a random image\n",
    "image_id = random.choice(dataset_val.image_ids)\n",
    "original_image, image_meta, gt_class_id, gt_bbox, gt_mask =\\\n",
    "    modellib.load_image_gt(dataset_val, inference_config, \n",
    "                           image_id, use_mini_mask=False)\n",
    "\n",
    "log(\"original_image\", original_image)\n",
    "log(\"image_meta\", image_meta)\n",
    "log(\"gt_class_id\", gt_class_id)\n",
    "log(\"gt_bbox\", gt_bbox)\n",
    "log(\"gt_mask\", gt_mask)\n",
    "\n",
    "visualize.display_instances(original_image, gt_bbox, gt_mask, gt_class_id, \n",
    "                            dataset_train.class_names, figsize=(8, 8))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "results = model.detect([original_image], verbose=1)\n",
    "\n",
    "r = results[0]\n",
    "visualize.display_instances(original_image, r['rois'], r['masks'], r['class_ids'], \n",
    "                            dataset_val.class_names, r['scores'], ax=get_ax())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Evaluation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# Compute VOC-Style mAP @ IoU=0.5\n",
    "# Running on 10 images. Increase for better accuracy.\n",
    "image_ids = np.random.choice(dataset_val.image_ids, 10)\n",
    "APs = []\n",
    "for image_id in image_ids:\n",
    "    # Load image and ground truth data\n",
    "    image, image_meta, gt_class_id, gt_bbox, gt_mask =\\\n",
    "        modellib.load_image_gt(dataset_val, inference_config,\n",
    "                               image_id, use_mini_mask=False)\n",
    "    molded_images = np.expand_dims(modellib.mold_image(image, inference_config), 0)\n",
    "    # Run object detection\n",
    "    results = model.detect([image], verbose=0)\n",
    "    r = results[0]\n",
    "    # Compute AP\n",
    "    AP, precisions, recalls, overlaps =\\\n",
    "        utils.compute_ap(gt_bbox, gt_class_id, gt_mask,\n",
    "                         r[\"rois\"], r[\"class_ids\"], r[\"scores\"], r['masks'])\n",
    "    APs.append(AP)\n",
    "    \n",
    "print(\"mAP: \", np.mean(APs))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
